### ISSUE TITLE
Add error handling for passing an invalid type in serversetup

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#439]
```
TypeError: path must be a string or Buffer
at TypeError (native)
at Object.fs.readdirSync (fs.js:953:18)
at setup (/home/rof/src/github.com/ansble/monument/routes/serverSetup.js:9:565)
at Proxy.assertThrows (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/core/assertions.js:2554:7)
at Proxy.methodWrapper (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
at Function.assert.throws (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/interface/assert.js:1973:16)
at Context.it (/home/rof/src/github.com/ansble/monument/routes/serverSetup_test.js:9:661)
at callFn (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:354:21)
at Test.Runnable.run (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:346:7)
at Runner.runTest (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:442:10)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:560:12
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:356:14)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:366:7
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:290:14)
at Immediate.<anonymous> (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:334:5)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5) undefined
```

Replace the generic node error handling with a type check and a thrown error with a better description of what is going on and what needs to be done to correct it.

**Comment by ignitionSoldier** [comment]
Hi.  I would like to take a crack at fixing this issue.  Is that okay?

**Comment by designfrontier** [comment]
Absolutely

**Comment by designfrontier** [comment]
Looks like #443 corrected this error as well
