### ISSUE TITLE
Fix test throwing an error

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#441]
```
{ Error: ENOTDIR: not a directory, scandir './test_stubs/routes_stub.json'
at Error (native)
at Object.fs.readdirSync (fs.js:953:18)
at setup (/home/rof/src/github.com/ansble/monument/routes/serverSetup.js:9:565)
at assert.throws (/home/rof/src/github.com/ansble/monument/routes/serverSetup_test.js:9:1025)
at Proxy.assertThrows (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/core/assertions.js:2554:7)
at Proxy.methodWrapper (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
at Function.assert.throws (/home/rof/src/github.com/ansble/monument/node_modules/chai/lib/chai/interface/assert.js:1973:16)
at Context.it (/home/rof/src/github.com/ansble/monument/routes/serverSetup_test.js:9:974)
at callFn (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:354:21)
at Test.Runnable.run (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runnable.js:346:7)
at Runner.runTest (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:442:10)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:560:12
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:356:14)
at /home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:366:7
at next (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:290:14)
at Immediate.<anonymous> (/home/rof/src/github.com/ansble/monument/node_modules/mocha/lib/runner.js:334:5)
at runCallback (timers.js:672:20)
at tryOnImmediate (timers.js:645:5)
at processImmediate [as _immediateCallback] (timers.js:617:5)
errno: -20,
code: 'ENOTDIR',
syscall: 'scandir',
path: './test_stubs/routes_stub.json' } './test_stubs/routes_stub.json'
```

One of the tests is throwing this error because it passing in a json file instead of a directory. Track it down and pass in the stub directory instead.

**Comment by haroon-sheikh** [comment]
I'll give it a go @designfrontier.
