### ISSUE TITLE
.send breaks when a rendered dot.js template is passed in.

### ISSUE THREAD

**Issue by designfrontier** [ansble/monument#62]
gets: 

```
/Users/designfrontier/projects/dfRedesign/node_modules/monument/utils/send.js:15
			that.setEncoding(encoding); //encoding header for the response
			     ^
TypeError: undefined is not a function
    at ServerResponse.send (/Users/designfrontier/projects/dfRedesign/node_modules/monument/utils/send.js:15:9)
    at EventEmitter.<anonymous> (/Users/designfrontier/projects/dfRedesign/routes/main.js:17:18)
    at EventEmitter.g (events.js:199:16)
    at EventEmitter.emit (events.js:107:17)
    at EventEmitter.<anonymous> (/Users/designfrontier/projects/dfRedesign/data/articles.js:465:10)
    at EventEmitter.emit (events.js:107:17)
    at EventEmitter.<anonymous> (/Users/designfrontier/projects/dfRedesign/routes/main.js:20:9)
    at EventEmitter.emit (events.js:107:17)
    at Server.<anonymous> (/Users/designfrontier/projects/dfRedesign/node_modules/monument/routes/index.js:253:11)
    at Server.emit (events.js:110:17)

```

**Comment by designfrontier** [comment]
or any string... for that matter
